### ISSUE TITLE
Memory Managment

### ISSUE THREAD

**Issue by jakebacker** [jakebacker/ULPM#20]
This is very important to do. This program currently **EATS** memory.

**Comment by simon-andrews** [comment]
I can't see anything obviously wrong in ulpm.cpp and a quick check with [Valgrind](http://valgrind.org/) doesn't show any memory leaks. What sort of issues are you having?

**Comment by jakebacker** [comment]
When I run the program many tines without restarting the computer, the memory usage starts going up and up.
